"""initial tables

Revision ID: a37ba5e06f56
Revises: 
Create Date: 2026-03-22 12:20:38.229390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37ba5e06f56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_saves',
    sa.Column('user_key', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('reputation_arts', sa.Integer(), nullable=False),
    sa.Column('reputation_engineering', sa.Integer(), nullable=False),
    sa.Column('reputation_medical', sa.Integer(), nullable=False),
    sa.Column('reputation_humanities', sa.Integer(), nullable=False),
    sa.Column('enrolled_students', sa.Integer(), nullable=False),
    sa.Column('average_student_level', sa.Float(), nullable=False),
    sa.Column('admission_policy', sa.String(length=16), nullable=False),
    sa.Column('admission_criteria', sa.JSON(), nullable=False),
    sa.Column('buildings', sa.JSON(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('pending_event', sa.String(length=64), nullable=True),
    sa.Column('bonus_freshmen', sa.Integer(), nullable=False),
    sa.Column('completed_milestones', sa.JSON(), nullable=False),
    sa.Column('active_quest_lines', sa.JSON(), nullable=False),
    sa.Column('completed_quests', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('admission_changed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_saves')
    # ### end Alembic commands ###
