export const palette = {
  sky: '#f5fbff',
  mint: '#d8f3dc',
  cream: '#fff7e8',
  peach: '#ffd9c8',
  butter: '#ffeaa6',
  lavender: '#e7dcff',
  coral: '#ff8f7a',
  navy: '#29445d',
  slate: '#62758a',
  white: '#ffffff',
  border: '#d7e4ee',
  shadow: '#aac4d61f',
  spring: '#e4f8d3',
  summer: '#d8f1ff',
  autumn: '#ffe2ba',
  winter: '#eef3ff',
  arts: '#ffb3c7',
  engineering: '#9ed7ff',
  medical: '#b7efc5',
  humanities: '#f8d488',
  success: '#5abf82',
  danger: '#ef6f6c',
};
